POP=calculator.commands.Pop
PUSH=calculator.commands.Push
+=calculator.commands.Add
-=calculator.commands.Sub
*=calculator.commands.Mul
/=calculator.commands.Div
SQRT=calculator.commands.Sqrt
PRINT=calculator.commands.Print
DEFINE=calculator.commands.Define